Add dry-run e2e test
Signed-off-by: Ian Lewis <ianlewis@google.com>

diff --git a/.github/workflows/pre-submit.units.yml b/.github/workflows/pre-submit.units.yml
--- a/.github/workflows/pre-submit.units.yml
+++ b/.github/workflows/pre-submit.units.yml
@@ -311,3 +311,48 @@ jobs:
         run: |
           # Close the test issue.
           gh issue close "${ISSUE_URL}" || true
+
+  issue-reopener-dry-run:
+    runs-on: ubuntu-latest
+    outputs:
+      issue-url: ${{ steps.create-issue.outputs.url }}
+    permissions:
+      issues: write
+    steps:
+      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+      - id: create-issue
+        env:
+          GH_TOKEN: ${{ github.token }}
+          PR_URL: ${{ github.event.pull_request.html_url }}
+        run: |
+          url=$(gh issue create --title "issue-reopener-dry-run pre-submit test issue" --body "Test issue for PR ${PR_URL}")
+          echo "${url}"
+          gh issue close "${url}"
+          mkdir test
+          echo "// TODO(${url}): still open" > test/test.go
+          echo "url=${url}" >> "${GITHUB_OUTPUT}"
+      - uses: ./actions/issue-reopener/
+        with:
+          path: "test/"
+          dry-run: true
+      - env:
+          GH_TOKEN: ${{ github.token }}
+          ISSUE_URL: ${{ steps.create-issue.outputs.url }}
+        run: |
+          # Ensure the issue was not reopened.
+          state=$(gh issue view "${ISSUE_URL}" --json state | jq -r '.state')
+          [ "${state}" == "CLOSED" ]
+
+  issue-reopener-dry-run-cleanup:
+    runs-on: ubuntu-latest
+    needs: issue-reopener-dry-run
+    if: ${{ always() }}
+    permissions:
+      issues: write
+    steps:
+      - env:
+          ISSUE_URL: ${{ needs.issue-reopener-dry-run.outputs.issue-url }}
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          # Ensure the the test issue is closed even if test fails.
+          gh issue close "${ISSUE_URL}" || true
